# Generated by Django 2.2.7 on 2019-11-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(db_column='username', default='', max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='first_name', max_length=30)),
                ('last_name', models.CharField(db_column='last_name', max_length=40)),
                ('email_address', models.CharField(db_column='email', max_length=50, unique=True)),
                ('bio', models.CharField(db_column='bio', default='bio', max_length=1000)),
                ('is_student', models.BooleanField(db_column='is_student', default=False)),
                ('is_mentor', models.BooleanField(db_column='is_mentor', default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type_name', models.CharField(choices=[('MR', 'Mentor'), ('ST', 'Student')], max_length=2)),
            ],
        ),
    ]
