# Generated by Django 2.2.7 on 2019-11-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191126_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(db_column='bio', default='bio', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.CharField(db_column='email', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(db_column='first_name', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(db_column='last_name', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_column='username', default='', max_length=20, primary_key=True, serialize=False),
        ),
    ]
