# Generated by Django 2.2.7 on 2019-11-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191126_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.CharField(db_column='email', max_length=50, unique=True),
        ),
    ]
