# Generated by Django 2.2.6 on 2019-12-06 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
