# Generated by Django 2.2.7 on 2019-11-26 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('company_address', models.CharField(max_length=200)),
                ('industry', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='industry.Industry')),
            ],
        ),
    ]
