# Generated by Django 2.2.7 on 2019-11-30 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='student',
        ),
    ]
