# Generated by Django 2.2.7 on 2019-11-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_type_name', models.CharField(choices=[('IY', 'Industry'), ('AC', 'Accounting'), ('AR', 'Airlines'), ('AG', 'Agriculture'), ('BN', 'Banking'), ('BV', 'Beverages'), ('ED', 'Education'), ('EG', 'Engineering'), ('EN', 'Environment'), ('FL', 'Film'), ('FD', 'Food'), ('HT', 'Health'), ('IN', 'Internet'), ('LW', 'Law'), ('MS', 'Music'), ('RD', 'Radio'), ('SP', 'Sports'), ('TC', 'Tech'), ('TV', 'Television'), ('TR', 'Transportation')], default='IY', max_length=2)),
            ],
        ),
    ]
