# Generated by Django 2.2.7 on 2019-11-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='majors',
        ),
        migrations.AddField(
            model_name='user',
            name='majors',
            field=models.ManyToManyField(to='app_user.Major'),
        ),
    ]
