# Generated by Django 2.2.7 on 2019-12-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='industry_type_name',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='major',
            name='major_name',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(max_length=30),
        ),
    ]
