# Generated by Django 2.2.7 on 2019-12-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_auto_20191130_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='industries',
            field=models.ManyToManyField(to='app_user.Industry'),
        ),
    ]
