# Generated by Django 2.2.7 on 2019-12-10 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_auto_20191210_0225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='industry',
            old_name='industry_type_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='major',
            old_name='major_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='school_name',
            new_name='name',
        ),
    ]
