# Generated by Django 2.2.7 on 2019-12-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_user_industries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='major_name',
            field=models.CharField(choices=[('--', '--'), ('AR', 'Art'), ('BI', 'Business'), ('CE', 'Civil Engineering'), ('CS', 'Computer Science'), ('FI', 'Film'), ('FN', 'Finance'), ('HI', 'History'), ('MT', 'Math'), ('MU', 'Music')], max_length=2),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type_name',
            field=models.CharField(choices=[('Resume', 'Resume'), ('Networking', 'Networking'), ('Interview', 'Interview'), ('Career Advice', 'Career Advice'), ('Job Search', 'Job Search'), ('Covder Letter', 'Cover Letter'), ('LinkedIn', 'LinkedIn'), ('Portfolio', 'Portfolio')], max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_name',
            field=models.CharField(choices=[('--', '--'), ('CL', 'Columbia University'), ('CC', 'CUNY City College'), ('HR', 'Harvard University'), ('YL', 'Yale University')], max_length=30),
        ),
    ]
