# Generated by Django 2.2.7 on 2019-12-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_auto_20191210_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='major',
            name='major_name',
            field=models.CharField(max_length=15),
        ),
    ]
