# Generated by Django 2.2.6 on 2019-12-06 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_auto_20191203_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyIndustry',
            fields=[
                ('industry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_user.Industry')),
            ],
            bases=('app_user.industry',),
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Connected')], default='P', max_length=1)),
                ('request_from', models.CharField(choices=[('P', 'Pending'), ('C', 'Connected')], default=None, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_user.Company')),
            ],
            bases=('app_user.company',),
        ),
        migrations.CreateModel(
            name='UserIndustry',
            fields=[
                ('industry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_user.Industry')),
            ],
            bases=('app_user.industry',),
        ),
        migrations.CreateModel(
            name='UserMajor',
            fields=[
                ('major_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_user.Major')),
            ],
            bases=('app_user.major',),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='', null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(default='default.jpg', null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_user.Request')),
            ],
            bases=('app_user.request',),
        ),
        migrations.CreateModel(
            name='UserSchool',
            fields=[
                ('school_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_user.School')),
            ],
            bases=('app_user.school',),
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.RemoveField(
            model_name='company',
            name='industries',
        ),
        migrations.RemoveField(
            model_name='user',
            name='companies',
        ),
        migrations.RemoveField(
            model_name='user',
            name='industries',
        ),
        migrations.RemoveField(
            model_name='user',
            name='majors',
        ),
        migrations.RemoveField(
            model_name='user',
            name='requests',
        ),
        migrations.RemoveField(
            model_name='user',
            name='schools',
        ),
        migrations.AlterField(
            model_name='industry',
            name='industry_type_name',
            field=models.CharField(choices=[('--', '--'), ('AC', 'Accounting'), ('AR', 'Airlines'), ('AG', 'Agriculture'), ('BN', 'Banking'), ('BV', 'Beverages'), ('ED', 'Education'), ('EG', 'Engineering'), ('EN', 'Environment'), ('FL', 'Film'), ('FD', 'Food'), ('HT', 'Health'), ('IN', 'Internet'), ('LW', 'Law'), ('MS', 'Music'), ('RD', 'Radio'), ('SP', 'Sports'), ('TC', 'Tech'), ('TV', 'Television'), ('TR', 'Transportation')], default='IY', max_length=2),
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='userschool',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_request', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermajor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userindustry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connection',
            name='mentor',
            field=models.ForeignKey(limit_choices_to={'is_mentor': True}, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_connection', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connection',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.CASCADE, related_name='student_connection', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyindustry',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.Company'),
        ),
    ]
