# Generated by Django 2.2.7 on 2019-12-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0005_auto_20191210_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='major_name',
            field=models.CharField(max_length=30),
        ),
    ]
