# Generated by Django 2.2.7 on 2019-12-10 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0007_auto_20191210_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_address',
        ),
    ]
