# Generated by Django 2.2.7 on 2019-12-10 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0010_auto_20191210_0415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='company',
            new_name='companies',
        ),
    ]
