# Generated by Django 2.2.6 on 2019-12-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0011_auto_20191210_0418'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
        migrations.AlterField(
            model_name='connection',
            name='request_from',
            field=models.CharField(choices=[('S', 'Student'), ('M', 'Mentor')], default=None, max_length=1, null=True),
        ),
    ]
