# Generated by Django 2.2.6 on 2019-12-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0012_auto_20191213_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='industry',
            name='industry_type_name',
        ),
        migrations.RemoveField(
            model_name='major',
            name='major_name',
        ),
        migrations.RemoveField(
            model_name='request',
            name='request_type_name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_address',
        ),
        migrations.RemoveField(
            model_name='school',
            name='school_name',
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='industry',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='major',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='request',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='school',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='companies',
            field=models.ManyToManyField(null=True, to='app_user.Company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='industries',
            field=models.ManyToManyField(null=True, to='app_user.Industry'),
        ),
        migrations.AlterField(
            model_name='user',
            name='majors',
            field=models.ManyToManyField(null=True, to='app_user.Major'),
        ),
        migrations.AlterField(
            model_name='user',
            name='requests',
            field=models.ManyToManyField(null=True, to='app_user.Request'),
        ),
        migrations.AlterField(
            model_name='user',
            name='schools',
            field=models.ManyToManyField(null=True, to='app_user.School'),
        ),
    ]
