# Generated by Django 2.2.6 on 2019-12-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0013_auto_20191213_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
