# Generated by Django 2.2.7 on 2019-12-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0018_auto_20191213_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='requests/documents/'),
        ),
    ]
