# Generated by Django 2.2.7 on 2019-12-16 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0020_userrequest_reqname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequest',
            old_name='reqname',
            new_name='label',
        ),
    ]
