# Generated by Django 2.2.7 on 2019-12-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0021_auto_20191215_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='label',
        ),
        migrations.AddField(
            model_name='userrequest',
            name='requesting',
            field=models.CharField(default='', max_length=100),
        ),
    ]
