# Generated by Django 2.2.7 on 2019-12-16 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0022_auto_20191215_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='student',
        ),
    ]
