# Generated by Django 2.2.7 on 2019-11-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorsearch', '0002_auto_20191119_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(height_field=20, upload_to='', width_field=20)),
            ],
        ),
    ]
