# Generated by Django 2.2.7 on 2019-11-25 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorsearch', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='school',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.RemoveField(
            model_name='student',
            name='major',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
        migrations.DeleteModel(
            name='Major',
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
